### ISSUE TITLE
"Hogfather" compatibility

### ISSUE THREAD

**Issue by nuno-silva** [zioth/dokuwik-anchor#3]
Hi!

The plugin is currently incompatible with the latest 2020-07-29 "Hogfather" dokuwiki release.

**Comment by zioth** [comment]
Happy to look into it. Could you provide some more information?
* The anchor syntax you're using (for example, `{{anchor:my_section}}`).
* The wiki syntax of the link (for example, `[[ns:page#my_section]]`)
* What happens when you click on the link?
* The template you're using. Any template that auto-scrolls to the top after page load will break this plugin.

**Comment by nuno-silva** [comment]
Thank you for the fast reply!

Unfortunately, it seems I confused this plugin with some other dokuwiki plugin/feature[1] and I can't find any page in my wiki using the `{{anchor:my_section}}` syntax.

Meanwhile, I see that you updated the [Anchor Plugin page](https://www.dokuwiki.org/plugin:anchor) to show that the plugin is compatible with Hogfather, so I think this can be closed.

Sorry for wasting your time :/

---

[1] PS: This is probably unrelated this issue, but if anyone knows about this, and just to clarify: before updating to Hogfather, there was a little anchor icon next to every page section that you could click and it would update the URL to point to that section. I'm not sure which plugin provided that feature :/ I'm using the bootstrap3 template.
